In [2]:
import numpy as np
from PIL import Image
import os

# 파일 -> 객체
img = Image.open('./data/cat.png').convert('L')
print("img:\n", img)
# 객체 -> array
img_array = np.array(img)
print("img_array:\n", img_array)
# array -> 파일
np.save('./data/lena_numpy', img_array)

# 파일 -> array
img_array = np.load('./data/lena_numpy.npy')
print("img_array:\n", img_array)
# array -> 객체
img = Image.fromarray(np.uint8(img_array))
print("img:\n", img)
# 객체 -> 파일
img.save('./data/lena_pil.png')

np_save_size = os.path.getsize('./data/lena_numpy.npy')
pil_save_size = os.path.getsize('./data/lena_pil.png')

print(f"numpy.save() 함수로 저장한 파일 크기: {np_save_size} bytes")
print(f"PIL.Image.fromarray() 함수로 저장한 파일 크기: {pil_save_size} bytes")

img:
 <PIL.Image.Image image mode=L size=310x162 at 0x272AA931E50>
img_array:
 [[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]
img_array:
 [[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]
img:
 <PIL.Image.Image image mode=L size=310x162 at 0x272AA7EA490>
numpy.save() 함수로 저장한 파일 크기: 50348 bytes
PIL.Image.fromarray() 함수로 저장한 파일 크기: 26813 bytes


In [3]:
import cv2
cv2.__version__

'4.5.5'